// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/jflex/SqlSanitizer.jflex

/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.java6.agent.instrumentation.jdbc.sql;

import java.util.regex.Pattern;


@SuppressWarnings("fallthrough")
final class AutoSqlSanitizer {

  /** This character denotes the end of file. */
  private static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 2048;

  // Lexical states.
  private static final int YYINITIAL = 0;
  private static final int DOLLAR_STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u1100\1\u1200\1\u1300\1\u1400\1\u1100\1\u1500\1\u1600"+
    "\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u1c00\1\u1100\1\u1d00"+
    "\1\u1e00\1\u1f00\12\u2000\1\u2100\1\u2200\1\u2300\1\u2000\1\u2400"+
    "\1\u2500\2\u2000\31\u1100\1\u2600\121\u1100\1\u2700\4\u1100\1\u2800"+
    "\1\u1100\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\1\u2e00\53\u1100"+
    "\1\u2f00\41\u2000\1\u1100\1\u3000\1\u3100\1\u1100\1\u3200\1\u3300"+
    "\1\u3400\1\u3500\1\u2000\1\u3600\1\u3700\1\u3800\1\u3900\1\u1100"+
    "\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u2000"+
    "\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u2000\1\u4d00\1\u4e00\1\u4f00"+
    "\1\u2000\3\u1100\1\u5000\1\u5100\1\u5200\12\u2000\4\u1100\1\u5300"+
    "\17\u2000\2\u1100\1\u5400\41\u2000\2\u1100\1\u5500\1\u5600\2\u2000"+
    "\1\u5700\1\u5800\27\u1100\1\u5900\2\u1100\1\u5a00\45\u2000\1\u1100"+
    "\1\u5b00\1\u5c00\11\u2000\1\u5d00\27\u2000\1\u5e00\1\u5f00\1\u6000"+
    "\1\u6100\11\u2000\1\u6200\1\u6300\5\u2000\1\u6400\1\u6500\4\u2000"+
    "\1\u6600\21\u2000\246\u1100\1\u6700\20\u1100\1\u6800\1\u6900\25\u1100"+
    "\1\u6a00\34\u1100\1\u6b00\14\u2000\2\u1100\1\u6c00\u0e05\u2000";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\2\22\0\1\1\1\0"+
    "\1\3\1\0\1\4\2\0\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\11\17\1\0"+
    "\1\20\5\0\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\41\4\0\1\41\1\52\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\41\57\0\1\41\12\0\1\41\4\0\1\41\5\0"+
    "\27\41\1\0\37\41\1\0\70\41\2\31\115\41\1\43"+
    "\u0142\41\4\0\14\41\16\0\5\41\7\0\1\41\1\0"+
    "\1\41\201\0\5\41\1\0\2\41\2\0\4\41\1\0"+
    "\1\41\6\0\1\41\1\0\3\41\1\0\1\41\1\0"+
    "\24\41\1\0\123\41\1\0\213\41\10\0\246\41\1\0"+
    "\46\41\2\0\1\41\6\0\51\41\107\0\33\41\4\0"+
    "\4\41\55\0\53\41\43\0\2\41\1\0\143\41\1\0"+
    "\1\41\17\0\2\41\7\0\2\41\12\0\3\41\2\0"+
    "\1\41\20\0\1\41\1\0\36\41\35\0\131\41\13\0"+
    "\1\41\30\0\41\41\11\0\2\41\4\0\1\41\5\0"+
    "\26\41\4\0\1\41\11\0\1\41\3\0\1\41\27\0"+
    "\31\41\7\0\13\41\65\0\25\41\1\0\10\41\106\0"+
    "\66\41\3\0\1\41\22\0\1\41\7\0\12\41\17\0"+
    "\20\41\4\0\10\41\2\0\2\41\2\0\26\41\1\0"+
    "\7\41\1\0\1\41\3\0\4\41\3\0\1\41\20\0"+
    "\1\41\15\0\2\41\1\0\3\41\16\0\2\41\12\0"+
    "\1\41\10\0\6\41\4\0\2\41\2\0\26\41\1\0"+
    "\7\41\1\0\2\41\1\0\2\41\1\0\2\41\37\0"+
    "\4\41\1\0\1\41\23\0\3\41\20\0\11\41\1\0"+
    "\3\41\1\0\26\41\1\0\7\41\1\0\2\41\1\0"+
    "\5\41\3\0\1\41\22\0\1\41\17\0\2\41\27\0"+
    "\1\41\13\0\10\41\2\0\2\41\2\0\26\41\1\0"+
    "\7\41\1\0\2\41\1\0\5\41\3\0\1\41\36\0"+
    "\2\41\1\0\3\41\17\0\1\41\21\0\1\41\1\0"+
    "\6\41\3\0\3\41\1\0\4\41\3\0\2\41\1\0"+
    "\1\41\1\0\2\41\3\0\2\41\3\0\3\41\3\0"+
    "\14\41\26\0\1\41\64\0\10\41\1\0\3\41\1\0"+
    "\27\41\1\0\20\41\3\0\1\41\32\0\3\41\5\0"+
    "\2\41\36\0\1\41\4\0\10\41\1\0\3\41\1\0"+
    "\27\41\1\0\12\41\1\0\5\41\3\0\1\41\40\0"+
    "\1\41\1\0\2\41\17\0\2\41\22\0\10\41\1\0"+
    "\3\41\1\0\51\41\2\0\1\41\20\0\1\41\5\0"+
    "\3\41\10\0\3\41\30\0\6\41\5\0\22\41\3\0"+
    "\30\41\1\0\11\41\1\0\1\41\2\0\7\41\72\0"+
    "\60\41\1\0\2\41\14\0\7\41\72\0\2\41\1\0"+
    "\1\41\1\0\5\41\1\0\30\41\1\0\1\41\1\0"+
    "\12\41\1\0\2\41\11\0\1\41\2\0\5\41\1\0"+
    "\1\41\25\0\4\41\40\0\1\41\77\0\10\41\1\0"+
    "\44\41\33\0\5\41\163\0\53\41\24\0\1\41\20\0"+
    "\6\41\4\0\4\41\3\0\1\41\3\0\2\41\7\0"+
    "\3\41\4\0\15\41\14\0\1\41\21\0\46\41\1\0"+
    "\1\41\5\0\1\41\2\0\53\41\1\0\u014d\41\1\0"+
    "\4\41\2\0\7\41\1\0\1\41\1\0\4\41\2\0"+
    "\51\41\1\0\4\41\2\0\41\41\1\0\4\41\2\0"+
    "\7\41\1\0\1\41\1\0\4\41\2\0\17\41\1\0"+
    "\71\41\1\0\4\41\2\0\103\41\45\0\20\41\20\0"+
    "\126\41\2\0\6\41\3\0\u016c\41\2\0\21\41\1\0"+
    "\32\41\5\0\113\41\6\0\10\41\7\0\15\41\1\0"+
    "\4\41\16\0\22\41\16\0\22\41\16\0\15\41\1\0"+
    "\3\41\17\0\64\41\43\0\1\41\4\0\1\41\103\0"+
    "\131\41\7\0\5\41\2\0\42\41\1\0\1\41\5\0"+
    "\106\41\12\0\37\41\61\0\36\41\2\0\5\41\13\0"+
    "\54\41\4\0\32\41\66\0\27\41\11\0\65\41\122\0"+
    "\1\41\135\0\57\41\21\0\7\41\67\0\36\41\15\0"+
    "\2\41\12\0\54\41\32\0\44\41\51\0\3\41\12\0"+
    "\44\41\2\0\11\41\7\0\53\41\2\0\3\41\51\0"+
    "\4\41\1\0\6\41\1\0\2\41\3\0\1\41\5\0"+
    "\300\41\100\0\26\41\2\0\6\41\2\0\46\41\2\0"+
    "\6\41\2\0\10\41\1\0\1\41\1\0\1\41\1\0"+
    "\1\41\1\0\37\41\2\0\65\41\1\0\7\41\1\0"+
    "\1\41\3\0\3\41\1\0\7\41\3\0\4\41\2\0"+
    "\6\41\4\0\15\41\5\0\3\41\1\0\7\41\164\0"+
    "\1\41\15\0\1\41\20\0\15\41\145\0\1\41\4\0"+
    "\1\41\2\0\12\41\1\0\1\41\3\0\5\41\6\0"+
    "\1\41\1\0\1\41\1\0\1\41\1\0\1\33\3\41"+
    "\1\0\13\41\2\0\4\41\5\0\5\41\4\0\1\41"+
    "\64\0\2\41\u017b\0\57\41\1\0\57\41\1\0\205\41"+
    "\6\0\4\41\3\0\2\41\14\0\46\41\1\0\1\41"+
    "\5\0\1\41\2\0\70\41\7\0\1\41\20\0\27\41"+
    "\11\0\7\41\1\0\7\41\1\0\7\41\1\0\7\41"+
    "\1\0\7\41\1\0\7\41\1\0\7\41\1\0\7\41"+
    "\120\0\1\41\325\0\2\41\52\0\5\41\5\0\2\41"+
    "\4\0\126\41\6\0\3\41\1\0\132\41\1\0\4\41"+
    "\5\0\53\41\1\0\136\41\21\0\33\41\65\0\306\41"+
    "\112\0\360\41\20\0\215\41\103\0\56\41\2\0\15\41"+
    "\3\0\20\41\12\0\2\41\24\0\57\41\20\0\37\41"+
    "\2\0\106\41\61\0\11\41\2\0\147\41\2\0\65\41"+
    "\2\0\5\41\60\0\13\41\1\0\3\41\1\0\4\41"+
    "\1\0\27\41\35\0\64\41\16\0\62\41\76\0\6\41"+
    "\3\0\1\41\1\0\2\41\13\0\34\41\12\0\27\41"+
    "\31\0\35\41\7\0\57\41\34\0\1\41\20\0\5\41"+
    "\1\0\12\41\12\0\5\41\1\0\51\41\27\0\3\41"+
    "\1\0\10\41\24\0\27\41\3\0\1\41\3\0\62\41"+
    "\1\0\1\41\3\0\2\41\2\0\5\41\2\0\1\41"+
    "\1\0\1\41\30\0\3\41\2\0\13\41\7\0\3\41"+
    "\14\0\6\41\2\0\6\41\2\0\6\41\11\0\7\41"+
    "\1\0\7\41\1\0\53\41\1\0\14\41\10\0\163\41"+
    "\35\0\244\41\14\0\27\41\4\0\61\41\4\0\156\41"+
    "\2\0\152\41\46\0\7\41\14\0\5\41\5\0\1\41"+
    "\1\0\12\41\1\0\15\41\1\0\5\41\1\0\1\41"+
    "\1\0\2\41\1\0\2\41\1\0\154\41\41\0\153\41"+
    "\22\0\100\41\2\0\66\41\50\0\14\41\164\0\5\41"+
    "\1\0\207\41\44\0\32\41\6\0\32\41\13\0\131\41"+
    "\3\0\6\41\2\0\6\41\2\0\6\41\2\0\3\41"+
    "\43\0\14\41\1\0\32\41\1\0\23\41\1\0\2\41"+
    "\1\0\17\41\2\0\16\41\42\0\173\41\205\0\35\41"+
    "\3\0\61\41\57\0\40\41\15\0\24\41\1\0\10\41"+
    "\6\0\46\41\12\0\36\41\2\0\44\41\4\0\10\41"+
    "\60\0\236\41\22\0\44\41\4\0\44\41\4\0\50\41"+
    "\10\0\64\41\234\0\67\41\11\0\26\41\12\0\10\41"+
    "\230\0\6\41\2\0\1\41\1\0\54\41\1\0\2\41"+
    "\3\0\1\41\2\0\27\41\12\0\27\41\11\0\37\41"+
    "\101\0\23\41\1\0\2\41\12\0\26\41\12\0\32\41"+
    "\106\0\70\41\6\0\2\41\100\0\1\41\17\0\4\41"+
    "\1\0\3\41\1\0\35\41\52\0\35\41\3\0\35\41"+
    "\43\0\10\41\1\0\34\41\33\0\66\41\12\0\26\41"+
    "\12\0\23\41\15\0\22\41\156\0\111\41\67\0\63\41"+
    "\15\0\63\41\15\0\44\41\334\0\35\41\12\0\1\41"+
    "\10\0\26\41\232\0\27\41\14\0\65\41\113\0\55\41"+
    "\40\0\31\41\32\0\44\41\35\0\1\41\13\0\43\41"+
    "\3\0\1\41\14\0\60\41\16\0\4\41\25\0\1\41"+
    "\1\0\1\41\43\0\22\41\1\0\31\41\124\0\7\41"+
    "\1\0\1\41\1\0\4\41\1\0\17\41\1\0\12\41"+
    "\7\0\57\41\46\0\10\41\2\0\2\41\2\0\26\41"+
    "\1\0\7\41\1\0\2\41\1\0\5\41\3\0\1\41"+
    "\22\0\1\41\14\0\5\41\236\0\65\41\22\0\4\41"+
    "\24\0\1\41\40\0\60\41\24\0\2\41\1\0\1\41"+
    "\270\0\57\41\51\0\4\41\44\0\60\41\24\0\1\41"+
    "\73\0\53\41\15\0\1\41\107\0\33\41\345\0\54\41"+
    "\164\0\100\41\37\0\1\41\240\0\10\41\2\0\47\41"+
    "\20\0\1\41\1\0\1\41\34\0\1\41\12\0\50\41"+
    "\7\0\1\41\25\0\1\41\13\0\56\41\23\0\1\41"+
    "\42\0\71\41\7\0\11\41\1\0\45\41\21\0\1\41"+
    "\61\0\36\41\160\0\7\41\1\0\2\41\1\0\46\41"+
    "\25\0\1\41\31\0\6\41\1\0\2\41\1\0\40\41"+
    "\16\0\1\41\u0147\0\23\41\15\0\232\41\346\0\304\41"+
    "\274\0\57\41\321\0\107\41\271\0\71\41\7\0\37\41"+
    "\161\0\36\41\22\0\60\41\20\0\4\41\37\0\25\41"+
    "\5\0\23\41\260\0\100\41\200\0\113\41\5\0\1\41"+
    "\102\0\15\41\100\0\2\41\1\0\1\41\34\0\370\41"+
    "\10\0\363\41\15\0\37\41\61\0\3\41\21\0\4\41"+
    "\10\0\u018c\41\4\0\153\41\5\0\15\41\3\0\11\41"+
    "\7\0\12\41\146\0\125\41\1\0\107\41\1\0\2\41"+
    "\2\0\1\41\2\0\2\41\2\0\4\41\1\0\14\41"+
    "\1\0\1\41\1\0\7\41\1\0\101\41\1\0\4\41"+
    "\2\0\10\41\1\0\7\41\1\0\34\41\1\0\4\41"+
    "\1\0\5\41\1\0\1\41\3\0\7\41\1\0\u0154\41"+
    "\2\0\31\41\1\0\31\41\1\0\37\41\1\0\31\41"+
    "\1\0\37\41\1\0\31\41\1\0\37\41\1\0\31\41"+
    "\1\0\37\41\1\0\31\41\1\0\10\41\64\0\55\41"+
    "\12\0\7\41\20\0\1\41\u0171\0\54\41\24\0\305\41"+
    "\73\0\104\41\7\0\1\41\264\0\4\41\1\0\33\41"+
    "\1\0\2\41\1\0\1\41\2\0\1\41\1\0\12\41"+
    "\1\0\4\41\1\0\1\41\1\0\1\41\6\0\1\41"+
    "\4\0\1\41\1\0\1\41\1\0\1\41\1\0\3\41"+
    "\1\0\2\41\1\0\1\41\2\0\1\41\1\0\1\41"+
    "\1\0\1\41\1\0\1\41\1\0\1\41\1\0\2\41"+
    "\1\0\1\41\2\0\4\41\1\0\7\41\1\0\4\41"+
    "\1\0\4\41\1\0\1\41\1\0\12\41\1\0\21\41"+
    "\5\0\3\41\1\0\5\41\1\0\21\41\104\0\327\41"+
    "\51\0\65\41\13\0\336\41\2\0\u0182\41\16\0\u0131\41"+
    "\37\0\36\41\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27904];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\1\1\3\1\1\1\4\1\5"+
    "\2\1\1\6\2\1\2\7\1\10\21\11\1\1\1\12"+
    "\1\13\1\0\1\14\1\0\1\3\2\0\1\7\1\15"+
    "\1\0\1\16\1\17\2\0\14\11\1\1\17\11\1\0"+
    "\1\3\2\0\1\20\1\7\2\0\34\11\1\21\1\7"+
    "\3\11\1\22\5\11\1\23\2\11\1\24\4\11\1\25"+
    "\1\26\1\11\1\27\6\11\1\30\1\11\1\31\1\32"+
    "\6\11\1\33\2\11\1\34\6\11\1\35\1\11\1\36"+
    "\1\11\1\37\3\11\1\40\1\41\6\11\1\42\2\11"+
    "\2\0\1\43";

  private static int [] zzUnpackAction() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\u0102\0\126"+
    "\0\126\0\u012d\0\u0158\0\126\0\u0183\0\u01ae\0\u01d9\0\u0204"+
    "\0\126\0\u022f\0\u025a\0\u0285\0\u02b0\0\u02db\0\u0306\0\u0331"+
    "\0\u035c\0\u0387\0\u03b2\0\u03dd\0\u0408\0\u0433\0\u045e\0\u0489"+
    "\0\u04b4\0\u04df\0\u050a\0\u0535\0\u0560\0\254\0\u058b\0\u05b6"+
    "\0\u05e1\0\u060c\0\u0102\0\u0637\0\126\0\u0158\0\u0662\0\126"+
    "\0\u068d\0\u06b8\0\u06e3\0\u070e\0\u0739\0\u0764\0\u078f\0\u07ba"+
    "\0\u07e5\0\u0810\0\u083b\0\u0866\0\u0891\0\u08bc\0\u025a\0\u08e7"+
    "\0\u0912\0\u093d\0\u0968\0\u0993\0\u09be\0\u09e9\0\u0a14\0\u0a3f"+
    "\0\u0a6a\0\u0a95\0\u0ac0\0\u0aeb\0\u0b16\0\u0b41\0\u050a\0\u0b6c"+
    "\0\u0b97\0\u0bc2\0\126\0\u068d\0\u0bed\0\u0c18\0\u0c43\0\u0c6e"+
    "\0\u0c99\0\u0cc4\0\u0cef\0\u0d1a\0\u0d45\0\u0d70\0\u0d9b\0\u0dc6"+
    "\0\u0df1\0\u0e1c\0\u0e47\0\u0e72\0\u0e9d\0\u0ec8\0\u0ef3\0\u0f1e"+
    "\0\u0f49\0\u0f74\0\u0f9f\0\u0fca\0\u0ff5\0\u1020\0\u104b\0\u1076"+
    "\0\u10a1\0\u10cc\0\126\0\126\0\u10f7\0\u0b6c\0\u1122\0\u025a"+
    "\0\u114d\0\u1178\0\u11a3\0\u11ce\0\u11f9\0\u025a\0\u1224\0\u124f"+
    "\0\u025a\0\u127a\0\u12a5\0\u12d0\0\u12fb\0\u025a\0\u025a\0\u1326"+
    "\0\u025a\0\u1351\0\u137c\0\u13a7\0\u13d2\0\u13fd\0\u1428\0\u025a"+
    "\0\u1453\0\u025a\0\u025a\0\u147e\0\u14a9\0\u14d4\0\u14ff\0\u152a"+
    "\0\u1555\0\u025a\0\u1580\0\u15ab\0\u025a\0\u15d6\0\u1601\0\u162c"+
    "\0\u1657\0\u1682\0\u16ad\0\u025a\0\u16d8\0\u025a\0\u1703\0\u025a"+
    "\0\u172e\0\u1759\0\u1784\0\u025a\0\u025a\0\u17af\0\u17da\0\u1805"+
    "\0\u1830\0\u185b\0\u1886\0\u025a\0\u18b1\0\u18dc\0\u1907\0\u1932"+
    "\0\126";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\13\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\23"+
    "\1\31\1\32\2\23\1\33\1\34\1\23\1\35\1\23"+
    "\1\36\1\37\1\40\1\41\1\42\3\23\1\43\4\44"+
    "\1\45\46\44\54\0\2\4\50\0\3\46\1\47\47\46"+
    "\4\0\1\50\11\0\2\51\1\0\31\52\1\0\5\53"+
    "\1\54\45\53\15\0\1\55\46\0\1\56\1\0\2\56"+
    "\1\0\2\20\44\0\1\56\1\0\1\57\1\56\1\0"+
    "\2\20\43\0\1\60\53\0\1\20\1\0\2\20\1\0"+
    "\2\20\5\0\1\20\22\0\1\61\13\0\1\20\1\0"+
    "\2\20\1\0\2\20\5\0\1\20\41\0\1\62\1\0"+
    "\2\23\1\0\13\23\1\63\15\23\15\0\1\62\1\0"+
    "\2\23\1\0\31\23\15\0\1\62\1\0\2\23\1\0"+
    "\1\64\6\23\1\65\6\23\1\66\2\23\1\67\7\23"+
    "\15\0\1\62\1\0\2\23\1\0\1\70\3\23\1\71"+
    "\14\23\1\72\7\23\15\0\1\62\1\0\2\23\1\0"+
    "\27\23\1\73\1\23\15\0\1\62\1\0\2\23\1\0"+
    "\21\23\1\74\7\23\15\0\1\62\1\0\2\23\1\0"+
    "\21\23\1\75\7\23\15\0\1\62\1\0\2\23\1\0"+
    "\3\23\1\76\1\23\1\77\6\23\1\100\1\101\13\23"+
    "\15\0\1\62\1\0\2\23\1\0\16\23\1\102\12\23"+
    "\15\0\1\62\1\0\2\23\1\0\4\23\1\103\24\23"+
    "\15\0\1\62\1\0\2\23\1\0\4\23\1\104\11\23"+
    "\1\105\12\23\15\0\1\62\1\0\2\23\1\0\1\106"+
    "\20\23\1\107\7\23\15\0\1\62\1\0\2\23\1\0"+
    "\4\23\1\110\24\23\15\0\1\62\1\0\2\23\1\0"+
    "\4\23\1\111\24\23\15\0\1\62\1\0\2\23\1\0"+
    "\1\112\30\23\15\0\1\62\1\0\2\23\1\0\17\23"+
    "\1\113\2\23\1\114\6\23\15\0\1\62\1\0\2\23"+
    "\1\0\1\115\7\23\1\116\20\23\1\0\52\117\1\120"+
    "\4\44\1\0\46\44\21\0\31\121\4\0\1\46\10\0"+
    "\1\62\36\0\4\50\1\122\46\50\16\0\2\51\37\0"+
    "\1\123\11\0\2\52\1\0\31\52\6\0\1\53\45\0"+
    "\2\57\1\0\50\57\16\0\2\124\1\0\6\124\27\0"+
    "\1\125\15\0\31\23\1\126\14\0\1\62\1\0\2\23"+
    "\1\0\23\23\1\127\5\23\15\0\1\62\1\0\2\23"+
    "\1\0\13\23\1\130\15\23\15\0\1\62\1\0\2\23"+
    "\1\0\4\23\1\131\24\23\15\0\1\62\1\0\2\23"+
    "\1\0\15\23\1\132\13\23\15\0\1\62\1\0\2\23"+
    "\1\0\4\23\1\133\24\23\15\0\1\62\1\0\2\23"+
    "\1\0\23\23\1\134\5\23\15\0\1\62\1\0\2\23"+
    "\1\0\13\23\1\135\15\23\15\0\1\62\1\0\2\23"+
    "\1\0\16\23\1\136\12\23\15\0\1\62\1\0\2\23"+
    "\1\0\10\23\1\137\6\23\1\140\11\23\15\0\1\62"+
    "\1\0\2\23\1\0\16\23\1\141\12\23\15\0\1\62"+
    "\1\0\2\23\1\0\1\142\30\23\15\0\1\62\1\0"+
    "\2\23\1\0\4\23\1\143\24\23\15\0\1\62\1\0"+
    "\2\23\1\0\17\23\1\140\11\23\15\0\1\62\1\0"+
    "\2\23\1\0\3\23\1\144\16\23\1\145\1\146\5\23"+
    "\15\0\1\62\1\0\2\23\1\0\10\23\1\147\20\23"+
    "\15\0\1\62\1\0\2\23\1\0\21\23\1\150\7\23"+
    "\15\0\1\62\1\0\2\23\1\0\27\23\1\151\1\23"+
    "\15\0\1\62\1\0\2\23\1\0\23\23\1\77\5\23"+
    "\15\0\1\62\1\0\2\23\1\0\22\23\1\152\6\23"+
    "\15\0\1\62\1\0\2\23\1\0\16\23\1\153\12\23"+
    "\15\0\1\62\1\0\2\23\1\0\2\23\1\154\26\23"+
    "\15\0\1\62\1\0\2\23\1\0\13\23\1\155\15\23"+
    "\15\0\1\62\1\0\2\23\1\0\1\23\1\156\27\23"+
    "\15\0\1\62\1\0\2\23\1\0\3\23\1\157\25\23"+
    "\15\0\1\62\1\0\2\23\1\0\4\23\1\160\24\23"+
    "\15\0\1\62\1\0\2\23\1\0\13\23\1\161\15\23"+
    "\15\0\1\62\1\0\2\23\1\0\4\23\1\162\24\23"+
    "\15\0\1\62\42\0\1\163\11\0\2\121\1\0\31\121"+
    "\5\0\1\164\46\0\3\125\1\165\47\125\52\126\1\166"+
    "\14\0\1\62\1\0\2\23\1\0\4\23\1\167\24\23"+
    "\15\0\1\62\1\0\2\23\1\0\13\23\1\170\15\23"+
    "\15\0\1\62\1\0\2\23\1\0\2\23\1\171\26\23"+
    "\15\0\1\62\1\0\2\23\1\0\15\23\1\172\13\23"+
    "\15\0\1\62\1\0\2\23\1\0\1\173\30\23\15\0"+
    "\1\62\1\0\2\23\1\0\1\174\30\23\15\0\1\62"+
    "\1\0\2\23\1\0\4\23\1\175\24\23\15\0\1\62"+
    "\1\0\2\23\1\0\17\23\1\176\11\23\15\0\1\62"+
    "\1\0\2\23\1\0\22\23\1\177\6\23\15\0\1\62"+
    "\1\0\2\23\1\0\16\23\1\200\12\23\15\0\1\62"+
    "\1\0\2\23\1\0\14\23\1\201\14\23\15\0\1\62"+
    "\1\0\2\23\1\0\15\23\1\202\13\23\15\0\1\62"+
    "\1\0\2\23\1\0\15\23\1\203\13\23\15\0\1\62"+
    "\1\0\2\23\1\0\4\23\1\204\24\23\15\0\1\62"+
    "\1\0\2\23\1\0\4\23\1\205\24\23\15\0\1\62"+
    "\1\0\2\23\1\0\16\23\1\206\12\23\15\0\1\62"+
    "\1\0\2\23\1\0\15\23\1\207\13\23\15\0\1\62"+
    "\1\0\2\23\1\0\6\23\1\210\22\23\15\0\1\62"+
    "\1\0\2\23\1\0\23\23\1\211\5\23\15\0\1\62"+
    "\1\0\2\23\1\0\22\23\1\212\6\23\15\0\1\62"+
    "\1\0\2\23\1\0\2\23\1\213\26\23\15\0\1\62"+
    "\1\0\2\23\1\0\16\23\1\214\12\23\15\0\1\62"+
    "\1\0\2\23\1\0\4\23\1\215\24\23\15\0\1\62"+
    "\1\0\2\23\1\0\13\23\1\216\15\23\15\0\1\62"+
    "\1\0\2\23\1\0\1\217\30\23\15\0\1\62\1\0"+
    "\2\23\1\0\21\23\1\220\7\23\15\0\1\62\1\0"+
    "\2\23\1\0\10\23\1\221\20\23\15\0\1\62\1\0"+
    "\2\23\1\0\26\23\1\220\2\23\4\0\1\125\10\0"+
    "\1\62\52\0\1\62\1\0\2\23\1\0\21\23\1\222"+
    "\7\23\15\0\1\62\1\0\2\23\1\0\12\23\1\223"+
    "\16\23\15\0\1\62\1\0\2\23\1\0\4\23\1\224"+
    "\24\23\15\0\1\62\1\0\2\23\1\0\23\23\1\225"+
    "\5\23\15\0\1\62\1\0\2\23\1\0\1\23\1\226"+
    "\27\23\15\0\1\62\1\0\2\23\1\0\23\23\1\227"+
    "\5\23\15\0\1\62\1\0\2\23\1\0\23\23\1\230"+
    "\5\23\15\0\1\62\1\0\2\23\1\0\21\23\1\231"+
    "\7\23\15\0\1\62\1\0\2\23\1\0\23\23\1\232"+
    "\5\23\15\0\1\62\1\0\2\23\1\0\23\23\1\233"+
    "\5\23\15\0\1\62\1\0\2\23\1\0\27\23\1\220"+
    "\1\23\15\0\1\62\1\0\2\23\1\0\21\23\1\234"+
    "\7\23\15\0\1\62\1\0\2\23\1\0\4\23\1\235"+
    "\24\23\15\0\1\62\1\0\2\23\1\0\26\23\1\236"+
    "\2\23\15\0\1\62\1\0\2\23\1\0\4\23\1\237"+
    "\24\23\15\0\1\62\1\0\2\23\1\0\25\23\1\240"+
    "\3\23\15\0\1\62\1\0\2\23\1\0\2\23\1\241"+
    "\26\23\15\0\1\62\1\0\2\23\1\0\4\23\1\220"+
    "\24\23\15\0\1\62\1\0\2\23\1\0\23\23\1\242"+
    "\5\23\15\0\1\62\1\0\2\23\1\0\3\23\1\243"+
    "\25\23\15\0\1\62\1\0\2\23\1\0\2\23\1\231"+
    "\26\23\15\0\1\62\1\0\2\23\1\0\4\23\1\244"+
    "\24\23\15\0\1\62\1\0\2\23\1\0\1\245\30\23"+
    "\15\0\1\62\1\0\2\23\1\0\4\23\1\246\24\23"+
    "\15\0\1\62\1\0\2\23\1\0\22\23\1\77\6\23"+
    "\15\0\1\62\1\0\2\23\1\0\23\23\1\223\5\23"+
    "\15\0\1\62\1\0\2\23\1\0\10\23\1\247\20\23"+
    "\15\0\1\62\1\0\2\23\1\0\23\23\1\250\5\23"+
    "\15\0\1\62\1\0\2\23\1\0\16\23\1\251\12\23"+
    "\15\0\1\62\1\0\2\23\1\0\3\23\1\252\25\23"+
    "\15\0\1\62\1\0\2\23\1\0\4\23\1\253\24\23"+
    "\15\0\1\62\1\0\2\23\1\0\23\23\1\254\5\23"+
    "\15\0\1\62\1\0\2\23\1\0\4\23\1\255\24\23"+
    "\15\0\1\62\1\0\2\23\1\0\1\256\30\23\15\0"+
    "\1\62\1\0\2\23\1\0\22\23\1\216\6\23\15\0"+
    "\1\62\1\0\2\23\1\0\5\23\1\257\23\23\15\0"+
    "\1\62\1\0\2\23\1\0\21\23\1\260\7\23\15\0"+
    "\1\62\1\0\2\23\1\0\24\23\1\261\4\23\15\0"+
    "\1\62\1\0\2\23\1\0\21\23\1\223\7\23\15\0"+
    "\1\62\1\0\2\23\1\0\23\23\1\262\5\23\15\0"+
    "\1\62\1\0\2\23\1\0\10\23\1\263\20\23\15\0"+
    "\1\62\1\0\2\23\1\0\3\23\1\264\25\23\15\0"+
    "\1\62\1\0\2\23\1\0\21\23\1\216\7\23\15\0"+
    "\1\62\1\0\2\23\1\0\4\23\1\223\24\23\15\0"+
    "\1\62\1\0\2\23\1\0\4\23\1\265\24\23\15\0"+
    "\1\62\1\0\2\23\1\0\3\23\1\266\25\23\2\0"+
    "\2\267\11\0\1\62\1\0\2\23\1\0\31\23\2\0"+
    "\2\267\17\0\1\270\101\0\1\271\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6493];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\4\1\2\11\2\1\1\11\4\1\1\11"+
    "\24\1\1\0\1\1\1\0\1\1\2\0\1\1\1\11"+
    "\1\0\1\1\1\11\2\0\34\1\1\0\1\1\2\0"+
    "\1\11\1\1\2\0\34\1\2\11\102\1\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  static SqlQuery sanitize(String statement, SqlDialect dialect) {
    AutoSqlSanitizer sanitizer = new AutoSqlSanitizer(new java.io.StringReader(statement));
    sanitizer.doubleQuotesAreIdentifiers = dialect.doubleQuotesAreIdentifiers();
    try {
      while (!sanitizer.yyatEOF()) {
        int token = sanitizer.yylex();
        // YYEOF token may be used to stop processing
        if (token == YYEOF) {
          break;
        }
      }
      return sanitizer.getResult();
    } catch (java.io.IOException e) {
      // should never happen
      return SqlQuery.create(null, null, null);
    }
  }

  // max length of the sanitized statement - SQLs longer than this will be trimmed
  static final int LIMIT = 32 * 1024;

  // Match on strings like "IN(?, ?, ...)"
  private static final Pattern IN_STATEMENT_PATTERN = Pattern.compile("(\\sIN\\s*)\\(\\s*\\?\\s*(?:,\\s*\\?\\s*)*+\\)", Pattern.CASE_INSENSITIVE);
  private static final String IN_STATEMENT_NORMALIZED = "$1(?)";

  private final StringBuilder builder = new StringBuilder();
  private String dollarTag = null;

  private void appendCurrentFragment() {
    builder.append(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
  }

  private boolean isOverLimit() {
    return builder.length() > LIMIT;
  }

  private String removeQuotes(String identifierName, String quote) {
    // remove quotes from the start and end of the identifier ("table" is transformed to table), if
    // identifier contains quote anywhere else besides start and end leave it as is (quotes are not
    // removed from "schema"."table")
    if (identifierName.startsWith(quote) && identifierName.endsWith(quote)) {
      String s = identifierName.substring(1, identifierName.length() - 1);
      if (!s.contains(quote)) {
        return s;
      }
    }
    return identifierName;
  }

  /** @return text matched by current token without enclosing double quotes or backticks */
  private String readIdentifierName() {
    String identifierName = yytext();
    if (identifierName != null) {
      String result = removeQuotes(identifierName, "\"");
      if (!result.equals(identifierName)) {
        return result;
      }
      result = removeQuotes(identifierName, "`");
      if (!result.equals(identifierName)) {
        return result;
      }
    }
    return identifierName;
  }

  // you can reference a table in the FROM clause in one of the following ways:
  //   table
  //   table t
  //   table as t
  // in other words, you need max 3 identifiers to reference a table
  private static final int FROM_TABLE_REF_MAX_IDENTIFIERS = 3;

  private int parenLevel = 0;
  private boolean insideComment = false;
  private Operation operation = NoOp.INSTANCE;
  private boolean extractionDone = false;
  private boolean doubleQuotesAreIdentifiers;
  private boolean statementStart = true;
  private boolean passwordSanitizationEnabled = false;
  private boolean identifiedBySanitizationEnabled = false;

  private void setOperation(Operation operation) {
    if (this.operation == NoOp.INSTANCE) {
      this.operation = operation;
    }
  }

  private void markStatementStarted() {
    statementStart = false;
  }

  private boolean shouldSanitizeRemainderAfterPassword() {
    return !insideComment
      && (passwordSanitizationEnabled
        || operation.shouldSanitizeRemainderAfterPassword());
  }

  private boolean shouldSanitizeRemainderAfterIdentifiedBy() {
    return !insideComment
      && (identifiedBySanitizationEnabled
        || operation.shouldSanitizeRemainderAfterIdentifiedBy());
  }

  private static abstract class Operation {
    String mainIdentifier = null;

    /** @return true if all statement info is gathered */
    boolean handleFrom() {
      return false;
    }

    /** @return true if all statement info is gathered */
    boolean handleInto() {
      return false;
    }

    /** @return true if all statement info is gathered */
    boolean handleJoin() {
      return false;
    }

    /** @return true if all statement info is gathered */
    boolean handleIdentifier() {
      return false;
    }

    /** @return true if all statement info is gathered */
    boolean handleComma() {
      return false;
    }

    /** @return true if all statement info is gathered */
    boolean handleNext() {
      return false;
    }

    /** @return true if all statement info is gathered */
    boolean handleOperationTarget(String target) {
      return false;
    }

    boolean expectingOperationTarget() {
      return false;
    }

    boolean shouldSanitizeRemainderAfterPassword() {
      return false;
    }

    boolean shouldSanitizeRemainderAfterIdentifiedBy() {
      return false;
    }

    SqlQuery getResult(String fullStatement) {
      return SqlQuery.create(fullStatement, getClass().getSimpleName().toUpperCase(java.util.Locale.ROOT), mainIdentifier);
    }
  }

  private abstract class DdlOperation extends Operation {
    private String operationTarget = "";
    private boolean expectingOperationTarget = true;

    boolean expectingOperationTarget() {
      return expectingOperationTarget;
    }

    boolean handleOperationTarget(String target) {
      operationTarget = target;
      expectingOperationTarget = false;
      return false;
    }

    boolean shouldHandleIdentifier() {
      // Return true only if the provided value corresponds to a table, as it will be used to set the attribute `db.sql.table`.
      return operationTarget.equalsIgnoreCase("TABLE");
    }

    /** Returns true for DDL targets where PASSWORD is treated as an identifier, not a secret clause. */
    boolean hasSafeDdlTarget() {
      return operationTarget.equalsIgnoreCase("TABLE")
          || operationTarget.equalsIgnoreCase("INDEX")
          || operationTarget.equalsIgnoreCase("PROCEDURE")
          || operationTarget.equalsIgnoreCase("VIEW");
    }

    boolean shouldSanitizeRemainderAfterPassword() {
      return !hasSafeDdlTarget();
    }

    boolean shouldSanitizeRemainderAfterIdentifiedBy() {
      return !hasSafeDdlTarget();
    }

    boolean handleIdentifier() {
      if (shouldHandleIdentifier()) {
        mainIdentifier = readIdentifierName();
      }
      return true;
    }

    SqlQuery getResult(String fullStatement) {
      if (!"".equals(operationTarget)) {
        return SqlQuery.create(fullStatement, getClass().getSimpleName().toUpperCase(java.util.Locale.ROOT) + " " + operationTarget, mainIdentifier);
      }
      return super.getResult(fullStatement);
    }
  }

  private static class NoOp extends Operation {
    static final Operation INSTANCE = new NoOp();

    SqlQuery getResult(String fullStatement) {
      return SqlQuery.create(fullStatement, null, null);
    }
  }

  private class Select extends Operation {
    // you can reference a table in the FROM clause in one of the following ways:
    //   table
    //   table t
    //   table as t
    // in other words, you need max 3 identifiers to reference a table
    private static final int FROM_TABLE_REF_MAX_IDENTIFIERS = 3;

    boolean expectingTableName = false;
    boolean mainTableSetAlready = false;
    int identifiersAfterMainFromClause = 0;

    boolean handleFrom() {
      if (parenLevel == 0) {
        // main query FROM clause
        expectingTableName = true;
        return false;
      }

      // subquery in WITH or SELECT clause, before main FROM clause; skipping
      mainIdentifier = null;
      return true;
    }

    boolean handleJoin() {
      // for SELECT statements with joined tables there's no main table
      mainIdentifier = null;
      return true;
    }

    boolean handleIdentifier() {
      if (identifiersAfterMainFromClause > 0) {
        ++identifiersAfterMainFromClause;
      }

      if (!expectingTableName) {
        return false;
      }

      // SELECT FROM (subquery) case
      if (parenLevel != 0) {
        mainIdentifier = null;
        return true;
      }

      // whenever >1 table is used there is no main table (e.g. unions)
      if (mainTableSetAlready) {
        mainIdentifier = null;
        return true;
      }

      mainIdentifier = readIdentifierName();
      mainTableSetAlready = true;
      expectingTableName = false;
      // start counting identifiers after encountering main from clause
      identifiersAfterMainFromClause = 1;

      // continue scanning the query, there may be more than one table (e.g. joins)
      return false;
    }

    boolean handleComma() {
      // comma was encountered in the FROM clause, i.e. implicit join
      // (if less than 3 identifiers have appeared before first comma then it means that it's a table list;
      // any other list that can appear later needs at least 4 idents)
      if (identifiersAfterMainFromClause > 0
          && identifiersAfterMainFromClause <= FROM_TABLE_REF_MAX_IDENTIFIERS) {
        mainIdentifier = null;
        return true;
      }
      return false;
    }
  }

  private class Insert extends Operation {
    boolean expectingTableName = false;

    boolean handleInto() {
      expectingTableName = true;
      return false;
    }

    boolean handleIdentifier() {
      if (!expectingTableName) {
        return false;
      }

      mainIdentifier = readIdentifierName();
      return true;
    }
  }

  private class Delete extends Operation {
    boolean expectingTableName = false;

    boolean handleFrom() {
      expectingTableName = true;
      return false;
    }

    boolean handleIdentifier() {
      if (!expectingTableName) {
        return false;
      }

      mainIdentifier = readIdentifierName();
      return true;
    }
  }

  /** Operation that extracts the first identifier as the main identifier. */
  private class SimpleOperation extends Operation {
    boolean handleIdentifier() {
      mainIdentifier = readIdentifierName();
      return true;
    }
  }

  private class Update extends SimpleOperation {}

  private class Merge extends SimpleOperation {}

  private class Call extends SimpleOperation {
    boolean handleNext() {
      mainIdentifier = null;
      return true;
    }
  }

  private class Create extends DdlOperation {}
  private class Drop extends DdlOperation {}
  private class Alter extends DdlOperation {}

  private SqlQuery getResult() {
    if (builder.length() > LIMIT) {
      builder.delete(LIMIT, builder.length());
    }
    String fullStatement = builder.toString();

    // Normalize all 'in (?, ?, ...)' statements to in (?) to reduce cardinality
    String normalizedStatement = IN_STATEMENT_PATTERN.matcher(fullStatement).replaceAll(IN_STATEMENT_NORMALIZED);

    return operation.getResult(normalizedStatement);
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AutoSqlSanitizer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  private final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  private final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  private final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  private final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  private final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  private final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  private final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  private final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  private int yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case DOLLAR_STRING: {
              // Unterminated dollar-quoted string - output what we have as ?
          builder.append('?');
          return YYEOF;
            }  // fall though
            case 186: break;
            default:
        return YYEOF;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 36: break;
          case 2:
            { builder.append(' ');
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 37: break;
          case 3:
            { if (!insideComment && !extractionDone) {
          extractionDone = operation.handleIdentifier();
        }
        appendCurrentFragment();
        if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 38: break;
          case 4:
            { if (!insideComment) {
            markStatementStarted();
            parenLevel += 1;
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 39: break;
          case 5:
            { if (!insideComment) {
            markStatementStarted();
            parenLevel -= 1;
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 40: break;
          case 6:
            { if (!insideComment && !extractionDone) {
            markStatementStarted();
            extractionDone = operation.handleComma();
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 41: break;
          case 7:
            { builder.append('?');
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 42: break;
          case 8:
            { if (!insideComment) {
            statementStart = true;
            passwordSanitizationEnabled = false;
            identifiedBySanitizationEnabled = false;
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 43: break;
          case 9:
            { if (!insideComment && !extractionDone) {
            markStatementStarted();
            extractionDone = operation.handleIdentifier();
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 44: break;
          case 10:
            { // Consume non-dollar characters
            }
          // fall through
          case 45: break;
          case 11:
            { // Single dollar sign, not part of a tag - continue consuming
            }
          // fall through
          case 46: break;
          case 12:
            { // Always notify the operation about double-quoted tokens regardless of dialect so
          // that table name extraction works correctly even when the dialect treats them as
          // string literals. For example, SELECT * FROM "my_table" should extract the table
          // name "my_table" whether or not the dialect sanitizes the token.
          //
          // The extractionDone guard ensures handleIdentifier() is a no-op once extraction
          // is complete, so there is no risk of leaking sensitive string content into the
          // span name.
          if (!insideComment && !extractionDone) {
            extractionDone = operation.handleIdentifier();
          }
          if (doubleQuotesAreIdentifiers) {
            appendCurrentFragment();
          } else {
            builder.append('?');
          }
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 47: break;
          case 13:
            { insideComment = false;
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 48: break;
          case 14:
            { // Line comment - append as-is, don't process keywords or sanitize literals
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 49: break;
          case 15:
            { insideComment = true;
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 50: break;
          case 16:
            { // Start of a tagged dollar-quoted string like $tag$...$tag$
          dollarTag = yytext();
          yybegin(DOLLAR_STRING);
            }
          // fall through
          case 51: break;
          case 17:
            { // Check if this is the closing tag
          if (yytext().equals(dollarTag)) {
            builder.append('?');
            dollarTag = null;
            yybegin(YYINITIAL);
            if (isOverLimit()) return YYEOF;
          }
          // else: different tag, continue consuming
            }
          // fall through
          case 52: break;
          case 18:
            { if (!insideComment) {
            markStatementStarted();
            setOperation(new Call());
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 53: break;
          case 19:
            { if (!insideComment) {
            markStatementStarted();
            setOperation(new Drop());
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 54: break;
          case 20:
            { if (!insideComment && !extractionDone) {
            markStatementStarted();
            if (operation == NoOp.INSTANCE) {
              // hql/jpql queries may skip SELECT and start with FROM clause
              // treat such queries as SELECT queries
              setOperation(new Select());
            }
            extractionDone = operation.handleFrom();
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 55: break;
          case 21:
            { if (!insideComment && !extractionDone) {
            markStatementStarted();
            extractionDone = operation.handleInto();
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 56: break;
          case 22:
            { if (!insideComment && !extractionDone) {
            markStatementStarted();
            extractionDone = operation.handleJoin();
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 57: break;
          case 23:
            { if (!insideComment && !extractionDone) {
            markStatementStarted();
            extractionDone = operation.handleNext();
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 58: break;
          case 24:
            { if (!insideComment && !extractionDone) {
            markStatementStarted();
            if (operation.expectingOperationTarget()) {
              extractionDone = operation.handleOperationTarget(yytext());
            } else {
              extractionDone = operation.handleIdentifier();
            }
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 59: break;
          case 25:
            { if (!insideComment) {
            markStatementStarted();
            setOperation(new Alter());
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 60: break;
          case 26:
            { if (!insideComment) {
            if (statementStart) {
              passwordSanitizationEnabled = true;
              identifiedBySanitizationEnabled = true;
            }
            markStatementStarted();
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 61: break;
          case 27:
            { if (!insideComment) {
            if (statementStart) {
              identifiedBySanitizationEnabled = true;
            }
            markStatementStarted();
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 62: break;
          case 28:
            { if (!insideComment) {
            markStatementStarted();
            setOperation(new Merge());
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 63: break;
          case 29:
            { if (!insideComment) {
            markStatementStarted();
            setOperation(new Create());
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 64: break;
          case 30:
            { if (!insideComment) {
            markStatementStarted();
            setOperation(new Delete());
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 65: break;
          case 31:
            { if (!insideComment) {
            markStatementStarted();
            setOperation(new Insert());
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 66: break;
          case 32:
            { if (!insideComment) {
            markStatementStarted();
            setOperation(new Select());
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 67: break;
          case 33:
            { if (!insideComment) {
            markStatementStarted();
            setOperation(new Update());
          }
          appendCurrentFragment();
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 68: break;
          case 34:
            { boolean passwordTokenIsIdentifier = false;
          if (!insideComment && !extractionDone) {
            markStatementStarted();
            passwordTokenIsIdentifier = operation.handleIdentifier();
            extractionDone = passwordTokenIsIdentifier;
          }
          appendCurrentFragment();
          if (!passwordTokenIsIdentifier && !insideComment && shouldSanitizeRemainderAfterPassword()) {
            builder.append(" ?");
            return YYEOF;
          }
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 69: break;
          case 35:
            { if (!insideComment) {
            markStatementStarted();
          }
          appendCurrentFragment();
          if (!insideComment && shouldSanitizeRemainderAfterIdentifiedBy()) {
            builder.append(" ?");
            return YYEOF;
          }
          if (isOverLimit()) return YYEOF;
            }
          // fall through
          case 70: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
